version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: coach-track-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: coach_tracking
    volumes:
      - mongodb_data:/data/db
    networks:
      - coach-network

  mongo-express:
    image: mongo-express:latest
    container_name: coach-track-mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - coach-network

volumes:
  mongodb_data:

networks:
  coach-network:
    driver: bridge
